const PASSWORD_ATTRIBUTE = 'password';
const EMAIL_ATTRIBUTE = 'email';
const APPLICATION_ID_ATTRIBUTE = 'applicationId';

const SESSION_TOKEN_DIR = 'session-token';
const SESSION_TOKEN_BKD = 'session-token-bkd';

const BEARER = 'Bearer ';
const ACCEPT = 'Accept';
const AUTHORIZATION = 'Authorization';
const CONTENT_TYPE = 'Content-Type';
const TRANSFER_ENCODING = 'transfer-encoding'

const FID_USER_ID = 'FID-USER-ID';
const FID_USER_ID_ANONYMOUS = 'anonymous';

const CONTENT_TYPE_APPLICATION_JSON = 'application/json';
const CONTENT_TYPE_X_FORM_URLENCODED = 'application/x-www-form-urlencoded';
const CONTENT_TYPE_MULTIPART_FORM_DATA = 'multipart/form-data';

const GET_METHOD = 'GET';
const PUT_METHOD = 'PUT';
const POST_METHOD = 'POST';
const PATCH_METHOD = 'PATCH';
const DELETE_METHOD = 'DELETE';

const FID_LOGGER_TRACKING_ID = 'FID-LOGGER-TRACKING-ID'
const NOT_FOUND_REQUEST_CODE_VALUE = 'DIS-FRONT-UI-FAIL';
const NOT_FOUND_REQUEST_TITLE = 'Invalid API request.'
const NOT_FOUND_REQUEST_DETAIL = 'Invalid API request, no backend API found for the request path.'

const BEARER_TOKEN_REGEX = /^Bearer\s[a-zA-Z0-9\-._~+/]+=*$/;

const HTTP_STATUS_CODE_200_OK = 200;
const HTTP_STATUS_CODE_201_CREATED = 201;
const HTTP_STATUS_CODE_500_SERVER_ERROR = 500;
const HTTP_STATUS_CODE_404_NOT_FOUND = 404;

const API_INVALID_URL_REQUEST_CODE_VALUE = 'DIS-FRONT-UI-FAIL';
const API_INVALID_URL_REQUEST_TITLE = 'Invalid API request.'
const API_INVALID_URL_REQUEST_DETAIL = 'Invalid API request, no backend API found for the request path.'
const API_FAILURE_REQUEST_CODE = 500;
const API_FAILURE_REQUEST_CODE_VALUE = 'DIS-FRONT-AP-FAIL';
const API_FAILURE_REQUEST_TITLE = 'Error in Downstream API.';
const API_FAILURE_REQUEST_DETAIL = 'Error in Downstream API, an non 2xx response was thrown when proxying downstream API.';

const INNER_API_V1_PATH = '/drb/api/v1';
const INNER_BACKBONE_PATH = '/bkd/api/v1';
const INNER_AUTH_PATH = `${INNER_API_V1_PATH}/auth`;
const INNER_GENERAL_PATH = `${INNER_API_V1_PATH}/general`;
const INNER_D_IMAGE_PATH = `${INNER_API_V1_PATH}/d-image`;
const INNER_VERIFY_CODE_PATH = `${INNER_API_V1_PATH}/verify-code`;
const INNER_CREATE_USER_PATH = `${INNER_AUTH_PATH}/create-user`;
const INNER_ACCESS_TOKEN_PATH = `${INNER_AUTH_PATH}/access-token`;

const BACKBONE_TOKEN_RELATIVE_PATH = '/backbone/api/v1/session/token';
const BACKBONE_TOKEN_RENEW_RELATIVE_PATH = '/backbone/api/v1/session/renew';

const DS_CREATE_USER_PATH = '/api/v1/users';
const DS_AUTH_RELATIVE_PATH = '/api/v1/auth';
const DS_CREATE_BUSINESS = '/api/v1/businesses';
const DS_TOKEN_RELATIVE_PATH = '/api/v1/session/token';
const DS_VERIFY_CODE_RELATIVE_PATH = '/api/v1/user-register';

const LOGGER_TAG_OAUTH_CLIENT = 'OATCLT';
const LOGGER_TAG_BACKBONE_CONTROLLER = 'BKNCTR';
const LOGGER_TAG_DIRECTORY_BACKEND_AUTH = 'DRBAUTH';
const LOGGER_TAG_DIRECTORY_BACKEND_REGISTER = 'DRBREG';
const LOGGER_TAG_DIRECTORY_BACKEND_STANDARD = 'DRBSTD';
const LOGGER_TAG_DIRECTORY_BACKEND_MULTIMEDIA = 'DRBMTD';
const LOGGER_TAG_DIRECTORY_BACKEND_CREATE_USER = 'DRBCUS';

module.exports = {
  PASSWORD_ATTRIBUTE,
  APPLICATION_ID_ATTRIBUTE,
  EMAIL_ATTRIBUTE,
  AUTHORIZATION,
  BEARER,
  SESSION_TOKEN_DIR,
  SESSION_TOKEN_BKD,
  FID_LOGGER_TRACKING_ID,
  FID_USER_ID_ANONYMOUS,
  HTTP_STATUS_CODE_404_NOT_FOUND,
  NOT_FOUND_REQUEST_CODE_VALUE,
  NOT_FOUND_REQUEST_TITLE,
  NOT_FOUND_REQUEST_DETAIL,

  // API error constants
  API_INVALID_URL_REQUEST_CODE_VALUE,
  API_INVALID_URL_REQUEST_DETAIL,
  API_INVALID_URL_REQUEST_TITLE,
  API_FAILURE_REQUEST_CODE,
  API_FAILURE_REQUEST_CODE_VALUE,
  API_FAILURE_REQUEST_TITLE,
  API_FAILURE_REQUEST_DETAIL,

  // Content types
  CONTENT_TYPE_MULTIPART_FORM_DATA,
  CONTENT_TYPE_X_FORM_URLENCODED,
  CONTENT_TYPE_APPLICATION_JSON,
  CONTENT_TYPE,

  FID_USER_ID,
  ACCEPT,
  BEARER_TOKEN_REGEX,

  // HTTP methods
  GET_METHOD,
  PUT_METHOD,
  POST_METHOD,
  PATCH_METHOD,
  DELETE_METHOD,

  // HTTP status codes
  HTTP_STATUS_CODE_200_OK,
  HTTP_STATUS_CODE_201_CREATED,
  HTTP_STATUS_CODE_500_SERVER_ERROR,

  TRANSFER_ENCODING,
  INNER_AUTH_PATH,
  INNER_D_IMAGE_PATH,
  INNER_GENERAL_PATH,
  INNER_BACKBONE_PATH,
  INNER_VERIFY_CODE_PATH,
  INNER_CREATE_USER_PATH,
  INNER_ACCESS_TOKEN_PATH,

  // Directory services paths
  DS_CREATE_BUSINESS,
  DS_CREATE_USER_PATH,
  DS_AUTH_RELATIVE_PATH,
  DS_TOKEN_RELATIVE_PATH,
  DS_VERIFY_CODE_RELATIVE_PATH,

  // Backbone paths
  BACKBONE_TOKEN_RELATIVE_PATH,
  BACKBONE_TOKEN_RENEW_RELATIVE_PATH,

  // Logger tags
  LOGGER_TAG_OAUTH_CLIENT,
  LOGGER_TAG_BACKBONE_CONTROLLER,
  LOGGER_TAG_DIRECTORY_BACKEND_AUTH,
  LOGGER_TAG_DIRECTORY_BACKEND_REGISTER,
  LOGGER_TAG_DIRECTORY_BACKEND_STANDARD,
  LOGGER_TAG_DIRECTORY_BACKEND_MULTIMEDIA,
  LOGGER_TAG_DIRECTORY_BACKEND_CREATE_USER
}
