const PASSWORD_ATTRIBUTE = 'password';
const SESSION_TOKEN_BKD = 'session-token-bkd';
const SESSION_TOKEN_DIR = 'session-token';
const AUTHORIZATION = 'Authorization';
const CONTENT_TYPE = 'Content-Type';
const FID_USER_ID = 'FID-USER-ID';
const BEARER = 'Bearer ';
const ACCEPT = 'Accept';
const TRANSFER_ENCODING = 'transfer-encoding';
const POST_METHOD = 'POST';
const FID_LOGGER_TRACKING_ID = 'FID-LOGGER-TRACKING-ID'
const NOT_FOUND_REQUEST_CODE = 404;
const NOT_FOUND_REQUEST_CODE_VALUE = 'DIS-FRONT-UI-FAIL';
const NOT_FOUND_REQUEST_TITLE = 'Invalid API request.'
const NOT_FOUND_REQUEST_DETAIL = 'Invalid API request, no backend API found for the request path.'

const BEARER_TOKEN_REGEX = /^Bearer\s[a-zA-Z0-9\-._~+/]+=*$/;

const API_INVALID_URL_REQUEST_CODE = 404;
const API_INVALID_URL_REQUEST_CODE_VALUE = 'DIS-FRONT-UI-FAIL';
const API_INVALID_URL_REQUEST_TITLE = 'Invalid API request.'
const API_INVALID_URL_REQUEST_DETAIL = 'Invalid API request, no backend API found for the request path.'
const API_FAILURE_REQUEST_CODE = 500;
const API_FAILURE_REQUEST_CODE_VALUE = 'DIS-FRONT-AP-FAIL';
const API_FAILURE_REQUEST_TITLE = 'Error in Downstream API.';
const API_FAILURE_REQUEST_DETAIL = 'Error in Downstream API, an non 2xx response was thrown when proxying downstream API.';
const CONTENT_TYPE_DEFAULT = 'application/json';

const INNER_AUTH_PATH = '/drb/api/v1/auth/access-token';
const INNER_VERIFY_CODE_PATH = '/drb/api/v1/verify-code';
const INNER_CREATE_USER_PATH = '/drb/api/v1/auth/create-user';

const BACKBONE_TOKEN_RELATIVE_PATH = '/backbone/api/v1/session/token';

const DS_CREATE_USER_PATH = '/api/v1/users';
const DS_AUTH_RELATIVE_PATH = '/api/v1/auth';
const DS_TOKEN_RELATIVE_PATH = '/api/v1/session/token';
const DS_VERIFY_CODE_RELATIVE_PATH = '/api/v1/user-register';

const LOGGER_TAG_BACKBONE_CONTROLLER = 'BKNCTR';
const LOGGER_TAG_DIRECTORY_BACKEND_AUTH = 'DRBAUTH';
const LOGGER_TAG_DIRECTORY_BACKEND_REGISTER = 'DRBREG';
const LOGGER_TAG_DIRECTORY_BACKEND_CREATE_USER = 'DRBCUS';
const LOGGER_TAG_OAUTH_CLIENT = 'OATCLT';

module.exports = {
  PASSWORD_ATTRIBUTE,
  AUTHORIZATION,
  BEARER,
  SESSION_TOKEN_DIR,
  SESSION_TOKEN_BKD,
  FID_LOGGER_TRACKING_ID,
  NOT_FOUND_REQUEST_CODE,
  NOT_FOUND_REQUEST_CODE_VALUE,
  NOT_FOUND_REQUEST_TITLE,
  NOT_FOUND_REQUEST_DETAIL,
  API_INVALID_URL_REQUEST_CODE,
  API_INVALID_URL_REQUEST_CODE_VALUE,
  API_INVALID_URL_REQUEST_DETAIL,
  API_INVALID_URL_REQUEST_TITLE,
  API_FAILURE_REQUEST_CODE,
  API_FAILURE_REQUEST_CODE_VALUE,
  API_FAILURE_REQUEST_TITLE,
  API_FAILURE_REQUEST_DETAIL,
  CONTENT_TYPE_DEFAULT,
  CONTENT_TYPE,
  FID_USER_ID,
  ACCEPT,
  BEARER_TOKEN_REGEX,
  POST_METHOD,
  TRANSFER_ENCODING,
  INNER_AUTH_PATH,
  INNER_VERIFY_CODE_PATH,
  INNER_CREATE_USER_PATH,
  DS_CREATE_USER_PATH,
  DS_AUTH_RELATIVE_PATH,
  DS_TOKEN_RELATIVE_PATH,
  DS_VERIFY_CODE_RELATIVE_PATH,
  BACKBONE_TOKEN_RELATIVE_PATH,
  LOGGER_TAG_BACKBONE_CONTROLLER,
  LOGGER_TAG_DIRECTORY_BACKEND_AUTH,
  LOGGER_TAG_DIRECTORY_BACKEND_REGISTER,
  LOGGER_TAG_DIRECTORY_BACKEND_CREATE_USER,
  LOGGER_TAG_OAUTH_CLIENT
}
